trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self
    persistCredentials: true
    clean: true

  - bash: |
      git checkout master
      git config --global user.email "binjr.bot@free.fr"
      git config --global user.name "binjr-bot"
      wget https://api.github.com/repos/binjr/binjr/releases/latest -O repos/binjr/binjr/releases/latest
      git commit -am "Update Github release info [skip azurepipelines]"
      git push
    displayName: 'Update Github release info'
