authors:
  fthevenet:
    name: Frederic Thevenet
    description: Maintainer
    avatar: https://github.com/fthevenet.png
  binjr:
    name: binjr
    description: binjr
    avatar: https://github.com/binjr.png